name: Scheduled Tasks

on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:

jobs:
  download:
    name: Download hosts files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Download and normalize hosts files
        run: |
          set -e

          declare -A FILES=(
            ["https://raw.githubusercontent.com/bigdargon/hostsVN/refs/heads/master/hosts"]="hostsVN.txt"
            ["https://raw.githubusercontent.com/bigdargon/hostsVN/refs/heads/master/extensions/adult/hosts"]="adult.txt"
            ["https://raw.githubusercontent.com/bigdargon/hostsVN/refs/heads/master/extensions/gambling/hosts"]="gambling.txt"
            ["https://raw.githubusercontent.com/bigdargon/hostsVN/refs/heads/master/extensions/threat/hosts"]="threat.txt"
          )

          for URL in "${!FILES[@]}"; do
            OUTPUT_FILE="${FILES[$URL]}"
            echo "Downloading $OUTPUT_FILE ..."

            curl -fsSL "$URL" \
              | grep -v '^#' \
              | sed -E 's/^0\.0\.0\.0[[:space:]]+(.+)/||\1^/' \
              > "$OUTPUT_FILE"

            echo "Created $OUTPUT_FILE"
          done

      - name: Upload inputs as artifact
        uses: actions/upload-artifact@v6
        with:
          name: inputs
          path: '*.txt'

  dead-domains:
    name: Dead Domains Linter
    runs-on: ubuntu-latest
    needs: download

    strategy:
      matrix:
        list:
          - input: threat.txt
            output: threat-DeadDomains.txt
          - input: adult.txt
            output: adult-DeadDomains.txt
          - input: gambling.txt
            output: gambling-DeadDomains.txt
          - input: hostsVN.txt
            output: hostsVN-DeadDomains.txt

    steps:
      - uses: actions/checkout@v6

      - name: Download input files
        uses: actions/download-artifact@v6
        with:
          name: inputs
          path: .

      - name: Install Dead Domains Linter
        run: npm i -g @adguard/dead-domains-linter

      - name: Run linter
        run: |
          dead-domains-linter \
            -i ${{ matrix.list.input }} \
            --export=${{ matrix.list.output }}

      - name: Cleanup input file
        run: rm -f ${{ matrix.list.input }}

      - name: Upload dead-domains result
        uses: actions/upload-artifact@v6
        with:
          name: dead-domains-results
          path: ${{ matrix.list.output }}

  commit-results:
    name: Commit All Dead Domains Results
    runs-on: ubuntu-latest
    needs: dead-domains

    steps:
      - uses: actions/checkout@v6

      - name: Download all dead-domains results
        uses: actions/download-artifact@v6
        with:
          name: dead-domains-results
          path: .

      - name: Commit and push outputs
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git status
          git add .
          git commit -m "chore: update dead-domains outputs" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
